# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'fasterer', '~> 0.1.9'
gem 'ffaker', '~> 2.11'
gem 'i18n', '~> 0.7.0'
gem 'rubocop', '~> 0.70.0'
