# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'faker', '~> 1.9', '>= 1.9.3'
gem 'fasterer', '~> 0.1.9'
gem 'ffaker', '~> 2.11'
gem 'rubocop', '~> 0.70.0'

